export const dashboardConfig = {
  code: 0,
  message: 'OK',
  data: [
    {
      id: 21,
      name: 'Dashboard',
      code: 'Dashboard',
      type: '',
      parentId: null,
      path: '/',
      redirect: '/dashboard/smart-house',
      icon: 'mdi-gauge',
      component: '/src/layout/index.vue',
      layout: null,
      keepAlive: null,
      method: null,
      description: null,
      show: true,
      enable: true,
      order: null,
      children: [
        {
          id: 24,
          name: 'Tesla Model S',
          code: 'teslaModelS',
          type: '',
          parentId: 21,
          path: '/dashboard/tesla-model-s',
          redirect: '',
          icon: 'mdi-alpha-t',
          component: '/src/views/dashboard/teslaModelS.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
        {
          id: 25,
          name: 'Smart House',
          code: 'smartHouse',
          type: '',
          parentId: 21,
          path: '/dashboard/smart-house',
          redirect: '',
          icon: 'mdi-alpha-s',
          component: '/src/views/dashboard/smartHouse.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
      ],
    },
    {
      id: 28,
      name: 'Componets',
      code: 'componets',
      type: '',
      parentId: null,
      path: '/componets',
      redirect: '/componets/table',
      icon: 'mdi-cube-scan',
      component: '/src/layout/index.vue',
      layout: null,
      keepAlive: null,
      method: null,
      description: null,
      show: true,
      enable: true,
      order: null,
      children: [
        {
          id: 29,
          name: 'Samples',
          code: 'samples',
          type: '',
          parentId: 28,
          path: '/componets/samples',
          redirect: '',
          icon: 'mdi-alpha-s',
          component: '/src/views/componets/sample.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
        {
          id: 30,
          name: 'table',
          code: 'Table',
          type: '',
          parentId: 28,
          path: '/componets/table',
          redirect: '',
          icon: 'mdi-alpha-t',
          component: '/src/views/componets/table.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
        {
          id: 31,
          name: 'calendar',
          code: 'Calendar',
          type: '',
          parentId: 28,
          path: '/componets/calendar',
          redirect: '',
          icon: 'mdi-alpha-c',
          component: '/src/views/componets/calendar.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
      ],
    },
    {
      id: 32,
      name: 'Graphics',
      code: 'graphics',
      type: '',
      parentId: null,
      path: '/graphics',
      redirect: '/graphics/babylonjs',
      icon: 'mdi-image',
      component: '/src/layout/index.vue',
      layout: null,
      keepAlive: null,
      method: null,
      description: null,
      show: true,
      enable: true,
      order: null,
      children: [
        {
          id: 33,
          name: 'Three.js',
          code: 'three-js',
          type: '',
          parentId: 32,
          path: '/graphics/three.js',
          redirect: '',
          icon: 'mdi-alpha-t',
          component: '/src/views/graphics/threeJs.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
        {
          id: 34,
          name: 'Pixi.js',
          code: 'Pixi-js',
          type: '',
          parentId: 32,
          path: '/graphics/pixi-js',
          redirect: '',
          icon: 'mdi-alpha-p',
          component: '/src/views/graphics/pixiJs.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
        {
          id: 35,
          name: 'Babylon.js',
          code: 'babylon-js',
          type: '',
          parentId: 32,
          path: '/graphics/babylon.js',
          redirect: '',
          icon: 'mdi-alpha-b',
          component: '/src/views/graphics/babylonjs.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
        {
          id: 35,
          name: 'Su7',
          code: 'Su7',
          type: '',
          parentId: 32,
          path: '/graphics/Su7',
          redirect: '',
          icon: 'mdi-alpha-s',
          component: '/src/views/graphics/su7Dashboard.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
      ],
    },
    {
      id: 36,
      name: 'Editor',
      code: 'editor',
      type: '',
      parentId: null,
      path: '/editor',
      redirect: '/editor/oreo-editor',
      icon: 'mdi-view-module',
      component: '/src/layout/index.vue',
      layout: null,
      keepAlive: null,
      method: null,
      description: null,
      show: true,
      enable: true,
      order: null,
      children: [
        {
          id: 37,
          name: 'Oreo Editor',
          code: 'oreo-editor',
          type: '',
          parentId: 36,
          path: '/editor/oreo-editor',
          redirect: '',
          icon: 'mdi-alpha-o',
          component: '/src/views/oreo-editor/index.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
      ],
    },
    {
      id: 38,
      name: 'Role-Based Access Control',
      code: 'RBAC',
      type: '',
      parentId: null,
      path: '/role-based-access-control',
      redirect: '/role-based-access-control/rbac',
      icon: 'mdi-account-supervisor-circle',
      component: '/src/layout/index.vue',
      layout: null,
      keepAlive: null,
      method: null,
      description: null,
      show: true,
      enable: true,
      order: null,
      children: [
        {
          id: 39,
          name: 'Roles',
          code: 'Roles',
          type: '',
          parentId: 38,
          path: '/role-based-access-control/roles',
          redirect: '',
          icon: 'mdi-alpha-r',
          component: '/src/views/rbac/index.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
        {
          id: 40,
          name: 'Users',
          code: 'Users',
          type: '',
          parentId: 38,
          path: '/role-based-access-control/user',
          redirect: '',
          icon: 'mdi-alpha-u',
          component: '/src/views/rbac/user.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
      ],
    },
    {
      id: 41,
      name: 'Tree Menu',
      code: 'treeMenu',
      type: '',
      parentId: null,
      path: '/tree-menu',
      redirect: '',
      icon: 'mdi-file-tree',
      component: '/src/layout/index.vue',
      layout: null,
      keepAlive: null,
      method: null,
      description: null,
      show: true,
      enable: true,
      order: null,
      children: [
        {
          id: 42,
          name: 'Two',
          code: 'Two',
          type: '',
          parentId: 41,
          path: '/aa/a1',
          redirect: '',
          icon: 'mdi-alpha-t',
          component: '/src/layout/index.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
          children: [
            {
              id: 43,
              name: 'Two1',
              code: 'Two1',
              type: '',
              parentId: 42,
              path: '/aa/a1/2d',
              redirect: '',
              icon: 'mdi-alpha-t',
              component: '/src/views/feedback/no.vue',
              layout: null,
              keepAlive: null,
              method: null,
              description: null,
              show: true,
              enable: true,
              order: null,
            },
          ],
        },
        {
          id: 44,
          name: 'One1',
          code: 'One1',
          type: '',
          parentId: 41,
          path: '/aa/a1/1d',
          redirect: '',
          icon: 'mdi-alpha-o',
          component: '/src/views/feedback/no.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
        {
          id: 45,
          name: 'One2',
          code: 'One2',
          type: '',
          parentId: 41,
          path: '/aa/a1/2d',
          redirect: '',
          icon: 'mdi-alpha-o',
          component: '/src/views/feedback/no.vue',
          layout: null,
          keepAlive: null,
          method: null,
          description: null,
          show: true,
          enable: true,
          order: null,
        },
      ],
    },
  ],
  originUrl: '/role/permissions/tree',
};
