/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomersAddModal: typeof import('./src/components/customers/CustomersAddModal.vue')['default']
    CustomersDeleteModal: typeof import('./src/components/customers/CustomersDeleteModal.vue')['default']
    HomeChart: typeof import('./src/components/home/HomeChart.vue')['default']
    HomeDateRangePicker: typeof import('./src/components/home/HomeDateRangePicker.vue')['default']
    HomePeriodSelect: typeof import('./src/components/home/HomePeriodSelect.vue')['default']
    HomeSales: typeof import('./src/components/home/HomeSales.vue')['default']
    HomeStats: typeof import('./src/components/home/HomeStats.vue')['default']
    InboxList: typeof import('./src/components/inbox/InboxList.vue')['default']
    InboxMail: typeof import('./src/components/inbox/InboxMail.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NotificationsSlideover: typeof import('./src/components/NotificationsSlideover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMembersList: typeof import('./src/components/settings/SettingsMembersList.vue')['default']
    TeamsMenu: typeof import('./src/components/TeamsMenu.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UChip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Chip.vue')['default']
    UDashboardGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardSearch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue')['default']
    UDashboardSearchButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    ULink: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    UsersAddModal: typeof import('./src/components/users/UsersAddModal.vue')['default']
    UsersDeleteModal: typeof import('./src/components/users/UsersDeleteModal.vue')['default']
    USlideover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
  }
}
